version: '3.9'

services:
  app:
    build:
      context: ./php
      args:
        UID: ${UID}
    volumes:
      - ../:/var/www/app
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    tty: true
    container_name: drom-php